name: Bob the Builder

on:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    container: debian:stable
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies ...
      run: |
        lsb_release -a
        sudo apt-get -y install tree libnet-dev
    - name: Configure & Build ...
      run: |
        ./autogen.sh
        ./configure --prefix=/usr CC=${{ matrix.compiler }}
        make V=1 -j5
        make install-strip DESTDIR=/tmp
        tree /tmp/usr
