name: Bob the Builder

on:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies ...
      run: |
        sudo apt-get install -y tree libnet-dev
    - name: Configure & Build ...
      run: |
        ./autogen.sh
        ./configure --prefix=/usr CC=${{ matrix.compiler }}
        make V=1 -j5
        make install-strip DESTDIR=/tmp
        tree /tmp/usr
  debian:
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies ...
      run: |
        apt-get update
        apt-get install -y build-essential autoconf automake libnet-dev dpkg-dev debhelper devscripts
    - name: Debian package ...
      run: |
        make package
