name: Coverity Scan
on:
  push:
    branches: [master]

env:
  PROJECT_NAME: nemesis
  CONTACT_EMAIL: troglobit@gmail.com
  COVERITY_NAME: libnet-nemesis
  COVERITY_NAME: troglobit%2Fnemesis

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: coverity-toolchain-cache
        with:
          path: cov-analysis-linux64
          key: ${{ runner.os }}-coverity
      - name: Install stuff
        run: ./tests/ci/install.sh
      - name: Download Coverity Scan
        if: steps.coverity-toolchain-cache.outputs.cache-hit != 'true'
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
        run: |
          wget -q https://scan.coverity.com/download/cxx/linux64 \
               --post-data "token=$TOKEN&project=${COVERITY_NAME}" \
               -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
      - name: Build
        run: |
          ./autogen.sh
          ./configure --with-snmp
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int make
      - name: Submit result to Coverity Scan
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
        run: |
          tar czvf ${PROJECT_NAME}.tgz cov-int
          curl \
            --form project=${COVERITY_NAME} \
            --form token=$TOKEN \
            --form email=${CONTACT_EMAIL} \
            --form file=@${PROJECT_NAME}.tgz \
            --form version=trunk \
            --form description="${PROJECT_NAME} $(git rev-parse HEAD)" \
            https://scan.coverity.com/builds?project=${COVERITY_NAME}
